import { useEffect } from 'react';
import Lenis from 'lenis';
import Head from 'next/head';
import Header from './Components/Header';
import MenuIntroduction from './Components/MenuIntroduction';
import Tiles from './Components/Tiles';
import FriesParallax from './Components/FriesParallax';
import Footer from './Components/Footer';
import RecomendedBurger from './Components/RecomendedBurger';

export default function Home() {
    useEffect(() => {
        const lenis = new Lenis();

        function raf(time) {
            lenis.raf(time);
            requestAnimationFrame(raf);
        }

        requestAnimationFrame(raf);
    }, []);

    return (
        <>
            <Head>
                <title>Fast Food</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/icon4.png' />
            </Head>
            <>
                <Header />
                <MenuIntroduction />
                <Tiles />
                <RecomendedBurger /> <FriesParallax />
                <Footer />
            </>
        </>
    );
}
